{% set name = "ucrt" %}
{% set version = "10.0.26100.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # from https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/
  url: https://go.microsoft.com/fwlink/?linkid=2272523
  fn: release_WindowsSDK.iso
  sha256: d075796a95cba563c3fc86e6dab10c17530d2b47d5dae3534fbfa7d3dfef541a

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
  host:
  run:
  run_constrained:
    - vs2015_runtime >=14.29.30037

test:
  commands:
    - if not exist %PREFIX%\\ucrtbase.dll exit 1
    - if not exist %LIBRARY_PREFIX%\\bin\\ucrtbase.dll exit 1

about:
  home: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
  license: LicenseRef-Proprietary
  license_file: LICENSE.txt
  summary: 'Redistributable files for Windows SDK. This is only needed Windows <10'

extra:
  recipe-maintainers:
    - isuruf
    - xhochy
